# Generated by Django 3.0.6 on 2020-05-18 17:43

import core_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, max_length=255, null=True, upload_to=core_app.models.file_dir)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
